### ISSUE TITLE
Agregar reglas de colaboración

### ISSUE THREAD

**Issue by jonathanwiesel** [codeheroco/codehero-static#90]
Se debe crear un archivo estilo CONTRIBUTING que especifique los parámetros que deben seguirse para contribuir al blog.

Cosas como tipo de contenido, estructura de una entrada, gestión externa de imágenes y manejo del repositorio.

**Comment by jonathanwiesel** [comment]
Agregado:

https://github.com/codeheroco/codehero-static/wiki/Contribuci%C3%B3n-de-entradas

@albertogg dime que piensas, en caso aprobatorio se puede cerrar este issue.

**Comment by albertogg** [comment]
Está bien. lo único que no entendí mucho fue esto:
>Procura tener tu entrada escrita antes de escribirla empezar en Prose, esto con la finalidad de no crear múltiples commits relacionados al mismo contenido en el repositorio.

De resto todo se entiende bien.

**Comment by jonathanwiesel** [comment]
@albertogg listo, la verborrea me confundio jaja

**Comment by albertogg** [comment]
Listo.
