### ISSUE TITLE
Las fechas en los posts se muestran en ingles

### ISSUE THREAD

**Issue by jonathanwiesel** [codeheroco/codehero-static#96]
Tanto en las listas de posts como en el detalle se ve el mes en ingles 

Por ejemplo dice "Publicado por X el 20 Apr 2014". (Apr de April, deberia ser Abr de Abril)

**Comment by jonathanwiesel** [comment]
Tenemos varias opciones:

* Utilizar un plugin de `i18n` con `locale` español para que tome el idioma.
* Utilizar un switch en la variable de la fecha para según el mes que sea cambiarlo por uno en español.
* Utilizar formato `dd/mm/yyyy` para que sean números en lugar de letras para el mes.

Que piensas @albertogg ?

**Comment by albertogg** [comment]
No estoy seguro, yo quiero la solución menos problemática. Capaz la última.

**Comment by jonathanwiesel** [comment]
Pienso lo mismo
